//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hungabor01Website.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hungabor01Website.Constants.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} happened at user {1}..
        /// </summary>
        public static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further assistance, please contact me on hungabor01@gmail.com.
        /// </summary>
        public static string ConfirmationEmailAssistance {
            get {
                return ResourceManager.GetString("ConfirmationEmailAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey,.
        /// </summary>
        public static string ConfirmationEmailBodyHey {
            get {
                return ResourceManager.GetString("ConfirmationEmailBodyHey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your registration. Please click to the link below to finish your registration..
        /// </summary>
        public static string ConfirmationEmailBodyThanks {
            get {
                return ResourceManager.GetString("ConfirmationEmailBodyThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation request from {0}..
        /// </summary>
        public static string ConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email claim not received from: {0}..
        /// </summary>
        public static string EmailClaimError {
            get {
                return ResourceManager.GetString("EmailClaimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be confirmed..
        /// </summary>
        public static string EmailConfirmationError {
            get {
                return ResourceManager.GetString("EmailConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already in use..
        /// </summary>
        public static string EmailIsTaken {
            get {
                return ResourceManager.GetString("EmailIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed yet..
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource could not be found..
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading external login information..
        /// </summary>
        public static string ExternalLoginError {
            get {
                return ResourceManager.GetString("ExternalLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from external provider: {0}..
        /// </summary>
        public static string ExternalProviderError {
            get {
                return ResourceManager.GetString("ExternalProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Attempt..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or email..
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email is sent. Please click on the link in the email..
        /// </summary>
        public static string NotifyUserConfirmationEmailSent {
            get {
                return ResourceManager.GetString("NotifyUserConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the confirmation email. Please try again signing up..
        /// </summary>
        public static string NotifyUserConfirmationEmailSentError {
            get {
                return ResourceManager.GetString("NotifyUserConfirmationEmailSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} is already in use..
        /// </summary>
        public static string UsernameIsTaken {
            get {
                return ResourceManager.GetString("UsernameIsTaken", resourceCulture);
            }
        }
    }
}
